version: '3.8'

services:
  infra:
    image: nginxproxy/nginx-proxy
    container_name: infra
    ports:
      - '25:25'
      # - '53:53'
      - '80:80'
      - '110:110'
      - '143:143'
      - '443:443'
      - '465:465'
      - '587:587'
      - '993:993'
      - '995:995'
      - '6379:6379'
      - '10025:10025'
      - '10143:10143'
      - '11332:11332'
      - '11334:11334'
      - '11335:11335'
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    networks:
      - aznable
  acme:
    image: nginxproxy/acme-companion
    container_name: acme
    volumes_from:
      - infra
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    networks:
      - aznable

networks:
  aznable:
    name: aznable

volumes:
  conf:
  vhost:
  certs:
  acme: