version: '3.8'

services:
  infra:
    image: nginxproxy/nginx-proxy
    container_name: infra
    ports:
      - '80:80'
      - '443:443'
      - '8888:8888'
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - aznable
  acme:
    image: nginxproxy/acme-companion
    container_name: acme
    volumes_from:
      - infra
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - aznable

networks:
  aznable:
    name: aznable

volumes:
  acme:
  certs:
  conf:
  html:
  vhost: